AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
    locash

    Sample SAM Template for locash

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 3

Resources:
    MessageHandlerFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: message-handler/
            Handler: app.lambdaHandler
            Runtime: nodejs12.x
            Events:
                Message:
                    Type: Api
                    Properties:
                        Path: /message
                        Method: post

Outputs:
    # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
    # Find out more about other implicit resources you can reference within SAM
    # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
    MessageHandlerApi:
        Description: "API Gateway endpoint URL for Prod stage for Message Handler function"
        Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/message/"
    MessageHandlerFunction:
        Description: "Message Handler Lambda Function ARN"
        Value: !GetAtt MessageHandlerFunction.Arn
    MessageHandlerFunctionIamRole:
        Description: "Implicit IAM Role created for Message Handler function"
        Value: !GetAtt MessageHandlerFunctionRole.Arn
