name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12 
        uses: actions/setup-node@v1
        with:
          version: 12 
      - run: npm install
      - run: npm check-all
        env:
          CI: true
