name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          version: 16 
      - run: npm ci
      - run: npm run eslint
      - run: npm run test  
        env:
          CI: true
