name: CICD

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          version: 12
      - run: npm install
      - run: npm run eslint
      - run: npm run test
        env:
          CI: true
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create credentials.json
        run: |
          echo '{"TELEGRAM_TOKEN": "$TELEGRAM_TOKEN"}' > message-handler/credentials.json
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      - uses: TractorZoom/sam-cli-action@master
        with:
          sam_command: "build"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create credentials.json
        run: |
          echo '{"TELEGRAM_TOKEN": "$TELEGRAM_TOKEN"}' > message-handler/credentials.json
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      - uses: TractorZoom/sam-cli-action@master
        with:
          sam_command: "deploy"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
